import type { NextPage } from 'next'
import Head from 'next/head'
import styles from './index.module.scss'
import NavBar from "../components/NavBar";
import PageHeader from "../components/PageHeader";
import {useState} from "react";
import {PricingPeriodType} from "../interfaces";
import PricingSwitch from "../components/PricingSwitch";

const Index: NextPage = () => {
  const [pricingPeriod, setPricingPeriod] = useState<PricingPeriodType>('month')
  console.log(pricingPeriod)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <main className={styles.main}>
        <PageHeader
          title={'Pricing'}
          subtitle={'Become a member & join over 300.000 other Hoppers today! Cryptohopper is free to use, create your free account now!'}
        />
        <PricingSwitch updateValue={setPricingPeriod} value={pricingPeriod} />
        {/*<PricingBlock prices={'monthly'}/>*/}

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}

export default Index
